services:
  api:
    build: .
    ports:
      - "8000:10000"
    environment:
      API_KEY: Iris@yajnas17!
      MAX_BATCH_SIZE: 100
      MODEL_VERSION: "1.0"
    volumes:
      - ./ml/saved_model:/app/ml/saved_model